language: python
dist: precise
python:
  - '2.7'
  - '3.6'
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de
install:
  - pip install .[test]
script:
  - travis_wait python -m pytest tests/
